# kubectl apply -f hct-alquiler-napaico-angelina-service.yml
apiVersion: v1
kind: Service
metadata:
  name: hct-alquiler-napaico-angelina-service
  namespace: hct-alquiler-napaico-angelina-namespace
spec:
  type: NodePort      #30000-32767  # Cambia a LoadBalancer si estás en un entorno de nube
  ports:
  - port: 30003       # Puerto que el Service expondrá
    targetPort: 9004  # Puerto en el contenedor donde tu aplicación escucha
    nodePort: 30003   # Puerto asignado en el nodo, opcional
  selector:
    app: hct-alquiler-napaico-angelina-deployment  # Debe coincidir con las etiquetas del Deployment