# MINIKUBE FUNCIONA EN CODESPACE | LOCAL
# KUBECTL FUNCIONA DIRECTO EN KILLERCODA (SIN MINIKUBE)

# consultar versión de minikube
minikube version

# consultar si minikube esta en start o stop
minikube status

# iniciar clúster kubernetes
minikube start

# ingresar a la carpeta de los manifiestos de kubernetes (manifest)
cd manifest

# listar namespace
kubectl get namespace
kubectl get ns

# crear un namespace "angelina" por comando mediante un archivo: "hct-alquiler-napaico-angelina-namespace.yml"
kubectl apply -f hct-alquiler-napaico-angelina-namespace.yml

# consultar namespace en uso por "default" | LINUX
kubectl config view --minify | grep namespace

# consultar namespace en uso por "default" | WINDOWS
kubectl config view --minify | findstr namespace

# cambiar un namespace en uso por "default" a "hct-alquiler-napaico-angelina-namespace"
kubectl config set-context --current --namespace=hct-alquiler-napaico-angelina-namespace

# consultar todos los recursos de un namespace "hct-alquiler-napaico-angelina-namespace"
kubectl get all -n hct-alquiler-napaico-angelina-namespace

# consultar todos los recursos y secret de un namespace "hct-alquiler-napaico-angelina-namespace"
kubectl get all,secrets -n hct-alquiler-napaico-angelina-namespace


# listar services del namespace "hct-alquiler-napaico-angelina-namespace"
minikube service hct-alquiler-napaico-angelina-service -n hct-alquiler-napaico-angelina-namespace
minikube service list

# probar el microservicio dentro del clúster con curl
curl http://192.168.49.2:30003/api/alquileres

# crear un túnel de puerto la máquina local (host) y el clúster de Kubernetes
kubectl port-forward service/hct-alquiler-napaico-angelina-service 8086:30003 -n hct-alquiler-napaico-angelina-namespace